version: "3"
services:
  webapp:
    build: .
    container_name: order-manager
    network_mode: host
    depends_on:
      postgres:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 20s
      retries: 10
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
